Unpin Postgres and set database password
There was a breaking change recently in Postgres Docker image [1],
where Postgres requires a password set.

As a quick fix, the postgres image was pinned
to the minor version 9.6.16 (before the change).

However, simply setting a password solves the issue
and is arguably a more robust way forward.

 - Set POSTGRES_PASSWORD environment variable to some password
   in the `postgres` container, via docker-compose

 - Update the `DATABASE_URL` connection string
   in `default.env` to include that password.

[1] Error message:
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD for the superuser. Use
       "-e POSTGRES_PASSWORD=password" to set it in "docker run".

       You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
       without a password. This is *not* recommended. See PostgreSQL
       documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

Reverts 961d0f4e7b703bbce82f17dfb0958f48eba7b333